name = "Opticraft"
author = "Lotus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1cd5fbef9a0e0a07971d879574b35a09b0d789e152b414cdfec02373e5d4558"

[versions]
fabric = "0.15.10"
minecraft = "1.20.4"
